### ISSUE TITLE
Keeping the components up to date

### ISSUE THREAD

**Issue by JimmyLv** [teovillanueva/shadcn-ui-react#1]

**Comment by teovillanueva** [comment]
Hey! Yeah it clearly didn't work 🤣 I have some ideas to bring this project again to life. I'll be opening a discussion soon.

**Comment by teovillanueva** [comment]
Just created a `next` branch. I will be pushing the new component generation code next week, and hoping to re-release all components :)

**Comment by JimmyLv** [comment]
This is absolutely amazing!

**Comment by teovillanueva** [comment]
Well, all of the component generation is done. I just have to setup the changesets cli and add a release workflow and its ready to go

**Comment by teovillanueva** [comment]
@JimmyLv Quick update, I've been very busy last week. I'll be trying to publish the components this week!

**Comment by teovillanueva** [comment]
Oh, Im also waiting for this PR to be merged before I can publish!
https://github.com/shadcn/ui/pull/462#issuecomment-1564674196

**Comment by jamesmurdza** [comment]
Also missing Command! Thank you.

**Comment by jamesmurdza** [comment]
I updated some components in #2.

**Comment by teovillanueva** [comment]
Hello, it's been a while since I paid any attention to this project, Im really sorry. The good news is that I revived it, since shadcn offers an endpoint with the components, now this repo runs a cronjob and checks against that endpoint to generate the components. Also the way the components are imported is far easier since you just import the component in any shadcn-style  (default/new-york) and it's corresponding css file. I'll be updating the readme to show how it works, but for now there is an example on the repo on how to use these components with nextjs!
